version: '3.8'

services:
  app:
    build: .
    ports:
      - "5454:5454"
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:mysql://mysql:3306/kra_foods
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=rootaditya
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootaditya
      - MYSQL_DATABASE=kra_foods
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data: 