services:
  - type: web
    name: adikrafoods-api
    env: docker
    rootDir: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 5454
      - key: DATABASE_URL
        fromDatabase:
          name: adikra-foods-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: adikra-foods-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: adikra-foods-db
          property: password

databases:
  - name: adikra-foods-db
    plan: free
    type: mysql 